version: '3.9'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: integration-tests-prisma
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5555:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   restart: unless-stopped
  
  
  redis:
    container_name: redis
    image: redis:7.0.12-alpine
    ports:
      - '6379:6379'

  api:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

    ports:
      - 8000:8000
      - 5555:5555
    command: npm run dev

# volumes:
#   pgadmin-data: